<script setup lang="ts">
import { ref, computed, watch, onMounted } from "vue";
import {
  createColumnHelper,
  getCoreRowModel,
  useVueTable,
  type ColumnDef,
} from "@tanstack/vue-table";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

interface TableProps {
  data: Record<string, any>[];
  columns?: ColumnDef<Record<string, any>>[];
}

const props = withDefaults(defineProps<TableProps>(), {
  data: () => [],
  columns: undefined,
});

const columnHelper = createColumnHelper<Record<string, any>>();

// 自动生成列
const autoGeneratedColumns = computed<ColumnDef<Record<string, any>>[]>(() => {
  if (props.data.length === 0) return [];

  const firstItem = props.data[0];
  return Object.keys(firstItem).map((key) =>
    columnHelper.accessor(key, {
      header: key,
      cell: (info) => info.getValue() ?? "-",
    })
  );
});

// 使用提供的列或自动生成的列
const columns = computed(() => props.columns || autoGeneratedColumns.value);

// 创建表格实例
const table = useVueTable({
  get data() {
    return props.data;
  },
  get columns() {
    return columns.value;
  },
  getCoreRowModel: getCoreRowModel(),
});

// 响应数据变化
watch(
  () => props.data,
  () => {
    // 表格会自动响应数据变化
  },
  { deep: true }
);
</script>

<template>
  <div class="rounded-md border">
    <Table>
      <TableHeader>
        <TableRow
          v-for="headerGroup in table.getHeaderGroups()"
          :key="headerGroup.id">
          <TableHead
            v-for="header in headerGroup.headers"
            :key="header.id"
            :colspan="header.colSpan"
            :class="header.column.columnDef.meta?.headerClass">
            <slot
              :name="`header-${header.column.id}`"
              :header="header"
              :column="header.column">
              {{ header.column.columnDef.header }}
            </slot>
          </TableHead>
        </TableRow>
      </TableHeader>

      <TableBody>
        <TableRow
          v-for="row in table.getRowModel().rows"
          :key="row.id"
          :class="row.getIsSelected() ? 'bg-muted/50' : ''">
          <TableCell
            v-for="cell in row.getVisibleCells()"
            :key="cell.id"
            :class="cell.column.columnDef.meta?.cellClass">
            <slot
              :name="`cell-${cell.column.id}`"
              :value="cell.getValue()"
              :row="row.original"
              :cell="cell">
              {{ cell.getValue() }}
            </slot>
          </TableCell>
        </TableRow>

        <TableRow v-if="table.getRowModel().rows.length === 0">
          <TableCell
            :colspan="columns.length"
            class="h-24 text-center">
            <slot name="empty">暂无数据</slot>
          </TableCell>
        </TableRow>
      </TableBody>
    </Table>
  </div>
</template>
