<script setup lang="ts">
import { ref, computed, watch, onMounted } from "vue";
import {
  createColumnHelper,
  getCoreRowModel,
  useVueTable,
  type ColumnDef,
} from "@tanstack/vue-table";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
interface TableProps {
  data: Record<string, any>[];
  columns?: Array<{
    prop: string;
    label: string;
    headerClass?: string;
    cellClass?: string;
    // 其他自定义属性...
  }>;
  alignCenter?: boolean;
}

const props = withDefaults(defineProps<TableProps>(), {
  data: () => [],
  columns: undefined,
  alignCenter: false,
});

const columnHelper = createColumnHelper<Record<string, any>>();

// 自动生成列
const autoGeneratedColumns = computed<ColumnDef<Record<string, any>>[]>(() => {
  if (props.columns) {
    return props.columns.map((col) => ({
      id: col.prop,
      accessorKey: col.prop,
      header: col.label,

      headerClass: col.headerClass,
      cellClass: col.cellClass,
      // 保留原始自定义属性
      original: col,
    }));
  }
  if (props.data.length === 0) return [];
  const firstItem = props.data[0];
  return Object.keys(firstItem).map((key) =>
    columnHelper.accessor(key, {
      header: key,
      cell: (info) => info.getValue() ?? "-",
    })
  );
});

// 创建表格实例
const table = useVueTable({
  get data() {
    return props.data;
  },
  get columns() {
    return autoGeneratedColumns.value;
  },
  getCoreRowModel: getCoreRowModel(),
});

// 响应数据变化
watch(
  () => props.data,
  () => {
    // 表格会自动响应数据变化
  },
  { deep: true }
);
</script>

<template>
  <div class="rounded-md border">
    <Table>
      <TableHeader>
        <TableRow
          v-for="headerGroup in table.getHeaderGroups()"
          :key="headerGroup.id">
          <TableHead
            v-for="header in headerGroup.headers"
            :key="header.id"
            :colspan="header.colSpan"
            class="!leading-10 bg-muted/50"
            :class="[header.column.columnDef?.headerClass]">
            <slot
              :name="`header-${header.column.id}`"
              :header="header"
              :column="header.column">
              {{ header.column.columnDef.header }}
            </slot>
          </TableHead>
        </TableRow>
      </TableHeader>

      <TableBody>
        <TableRow
          v-for="row in table.getRowModel().rows"
          :key="row.id"
          class="cursor-pointer hover:bg-muted/50 !leading-7 align-middle"
          :class="[row.getIsSelected() ? 'bg-muted/50' : '']">
          <TableCell
            v-for="cell in row.getVisibleCells()"
            :key="cell.id"
            class="max-w-3xs truncate"
            :class="cell.column.columnDef?.cellClass">
            <slot
              :name="`cell-${cell.column.id}`"
              :value="cell.getValue()"
              :row="row.original"
              :cell="cell">
              {{ cell.getValue() }}
            </slot>
          </TableCell>
        </TableRow>

        <TableRow v-if="table.getRowModel().rows.length === 0">
          <TableCell
            :colspan="columns.length"
            class="h-24 text-center">
            <slot name="empty">暂无数据</slot>
          </TableCell>
        </TableRow>
      </TableBody>
    </Table>
  </div>
</template>
